name: Build and Test
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@main

      - name: Install .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "10.0.x"

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Tests
        run: dotnet test